export { default as HomeHeader } from './HomeHeader'
export { default as FocusedStatusBar } from './FocusedStatusBar'
export { default as NFTCard } from './NFTCard'
export { default as DetailsDesc } from './DetailsDesc'
export { default as DetailsBid } from './DetailsBid'